apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8080 # porta cluster
      targetPort: 8080 # porta container aplicaçao
      nodePort: 30080 # porta exposta host
  type: NodePort
