apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  labels:
    app: api
data:
  ConnectionStringSQL: "Server=mssql-service,1450;Database=FIAP;User Id=sa;Password=Fiap@2024;"
  RabbitMQ__Host: "rabbitmq-service"
  RabbitMQ__Port: "5672"
  Logging__LogLevel__Default: "Information"
