apiVersion: v1
kind: Service
metadata:
  name: mssql-service
  labels:
    app: mssql
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1450
      targetPort: 1433
      nodePort: 30433
  type: NodePort
