apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq-container
          image: rabbitmq:3-management # Versão com interface de gerenciamento
          ports:
            - containerPort: 5672 # Porta de comunicação
            - containerPort: 15672 # Porta de gerenciamento
