name: TechChallenge-Modulo-3-Fiap

on:
  push:
    branches: [ "main", "feature/**", "bugfix/**", fase4Desenvolvimento ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with: 
          dotnet-version: 8.0.x
          
      - name: Restore dependencies
        run: dotnet restore ./TechChallenge_Contatos_DDD.sln
        
      - name: Build
        run: dotnet build ./TechChallenge_Contatos_DDD.sln --no-restore
        
  unit_tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Run unit tests
        run: dotnet test ./Tests/UnitTests/Tests.csproj --configuration Debug --collect:"XPlat Code Coverage"
        
  integration_tests:
    runs-on: ubuntu-latest
    needs: unit_tests

    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
          - 1450:1433
        env:
          SA_PASSWORD: "Fiap@2024"
          ACCEPT_EULA: "Y"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x

      - name: Run integration tests
        env:
          ConnectionStrings__DefaultConnection: "Server=localhost;Database=FIAP;User Id=sa;Password=Fiap@2024;"
        run: dotnet test ./Tests/IntegrationTests/IntegrationTests.csproj --configuration Release --filter Category=Integration
